distributed.nanny - INFO -         Start Nanny at: 'tcp://172.20.5.205:36885'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/site-packages/distributed/process.py", line 191, in _run
    target(*args, **kwargs)
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/site-packages/distributed/nanny.py", line 672, in _run
    worker = Worker(**worker_kwargs)
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/site-packages/distributed/worker.py", line 505, in __init__
    self._workspace = WorkSpace(os.path.abspath(local_directory))
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/site-packages/distributed/diskutils.py", line 118, in __init__
    self._init_workspace()
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/site-packages/distributed/diskutils.py", line 124, in _init_workspace
    os.mkdir(self.base_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/juliec/.dask_logs/mti_nma/2020-03-19T11:50:49'
distributed.nanny - INFO - Worker process 5921 exited with status 1
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f3620552a90>>, <Task finished coro=<Nanny._on_exit() done, defined at /home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/site-packages/distributed/nanny.py:393> exception=TypeError('addresses should be strings or tuples, got None')>)
Traceback (most recent call last):
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/site-packages/distributed/nanny.py", line 396, in _on_exit
    await self.scheduler.unregister(address=self.worker_address)
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/site-packages/distributed/core.py", line 757, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/site-packages/distributed/core.py", line 556, in send_recv
    raise exc.with_traceback(tb)
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/site-packages/distributed/core.py", line 408, in handle_comm
    result = handler(comm, **msg)
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/site-packages/distributed/scheduler.py", line 2136, in remove_worker
    address = self.coerce_address(address)
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/site-packages/distributed/scheduler.py", line 4845, in coerce_address
    raise TypeError("addresses should be strings or tuples, got %r" % (addr,))
TypeError: addresses should be strings or tuples, got None
distributed.nanny - INFO - Closing Nanny at 'tcp://172.20.5.205:36885'
distributed.dask_worker - INFO - End worker
